name: CD

on:
    push:
      branches:
        - dev

jobs:
    deploy:
      name: deploy
      runs-on: ubuntu-latest

      steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          echo "Successfully pulled repo."
      - name: connect and pull
        run: |
          echo ${{ secrets.SSH_USER }} - ${{ secrets.SSH_HOST }}
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "deploy-backend && exit"
      - name: cleanup
        run: rm -rf ~/.ssh